[project]
name = "yhwh"
version = "0.0.1"
authors = [
    { name="Jason Wilkes", email="notarealdeveloper@gmail.com" },
]
description = "Biblical Hebrew verb conjugator."
dependencies = [
    "pytest",
]

[project.scripts]
yhwh = "yhwh.__main__:main"

[project.urls]
source = "https://github.com/notarealdeveloper/yhwh"
download = "https://pypi.org/project/yhwh/#files"
